
###############################################################################
#
# Zabbix web:
# - URL: http://localhost:8080
# - User: Admin
# - Password: zabbix
#
###############################################################################

version: '3'

services:
  
  zabbix-mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
    networks:
      main:
        aliases:
          - zabbix-mariadb

  zabbix-server:
    build:
      context: ./zabbix-server-custom
      args:
        - http_proxy
        - https_proxy
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - DB_SERVER_HOST=zabbix-mariadb
      - MYSQL_USER=zabbix_user
      - MYSQL_PASSWORD=zabbix_password
      - http_proxy
      - https_proxy
    networks:
      main:
        aliases:
          - zabbix-server

  zabbix-web:
    build:
      context: ./zabbix-web-custom
      args:
        - http_proxy
        - https_proxy
    environment:
      - DB_SERVER_HOST=zabbix-mariadb
      - MYSQL_USER=zabbix_user
      - MYSQL_PASSWORD=zabbix_password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ
      - http_proxy
      - https_proxy
    ports:
      - 8080:80/tcp
    networks:
      main:
        aliases:
          - zabbix-web

  zabbix-agent1:
    build:
      context: ./zabbix-agent-custom
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    networks:
      main:

  zabbix-agent2:
    build:
      context: ./zabbix-agent-custom
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    networks:
      main:

  zabbix-agent3:
    build:
      context: ./zabbix-agent-custom
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    networks:
      main:

networks:
  main:

